oauth :
  google :
    client-id : ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret : ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri : ${OAUTH_GOOGLE_REDIRECT_URI}
    token-uri : https://oauth2.googleapis.com/token
    resource-uri : https://www.googleapis.com/oauth2/v2/userinfo
